server:
  port: 8083
  servlet:
    session:
      timeout: 30ms

spring:
  cache:
    type: redis
  redis:
#    host: 127.0.0.1
    host: 172.18.90.9
    port: 6379
    password:
      # redis默认情况下有16个分片, 这里配置具体使用的分片, 默认为0
    database: 0
    letture:
      pool:
        # 连接池最大连接数(使用负数表示没有限制), 默认0
        max-active: 100
